# 系統配置
system:
  max_concurrent_tasks: 3
  task_timeout_hours: 24
  cleanup_completed_tasks_days: 7

# 資源配置
resources:
  gpu_memory_fraction: 0.8
  max_workers: 4
  batch_size: 64

# 儲存配置
storage:
  temp_dir: "/tmp/auto_training"
  results_retention_days: 30
  auto_cleanup: true

# 日誌配置
logging:
  level: "INFO"
  file: "logs/auto_training.log"
  max_size_mb: 100
  backup_count: 5
 
train_config_path: "configs/train_configs.yaml"

# 資料庫配置檔案路徑
database_config_path: "configs/configs.json"