database_config_path: backend/configs/database_configs.json
logging:
  backup_count: 5
  file: logs/auto_training.log
  level: INFO
  max_size_mb: 100
resources:
  batch_size: 8
  gpu_memory_fraction: 0.8
  max_workers: 4
storage:
  auto_cleanup: true
  results_retention_days: 30
  temp_dir: /tmp/auto_training
system:
  cleanup_completed_tasks_days: 7
  max_concurrent_tasks: 2
  task_timeout_hours: 24
train_config_path: backend/configs/train_configs.yaml
