data:
  data_dir: /path/to/dataset
  image_size: 224
  num_workers: 4
  test_split: 0.2
experiment:
  name: hoam_experiment
knn:
  dataset_pkl: dataset.pkl
  enable: false
  index_path: knn.index
  threshold: 0.5
loss:
  center_loss_weight: 0.01
  sub_centers: 3
  subcenter_margin: 0.4
  subcenter_scale: 30.0
  triplet_margin: 0.3
  type: HybridMarginLoss
model:
  backbone: efficientnetv2_rw_s
  embedding_size: 512
  pretrained: false
  structure: HOAMV2
training:
  batch_size: 8
  checkpoint_dir: checkpoints
  enable_early_stopping: true
  freeze_backbone_epochs: 10
  lr: 0.0003
  max_epochs: 60
  min_epochs: 0
  patience: 10
  weight_decay: 0.0001
